knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
server:
  port: 8081
spring:
  # ElasticSearch配置
  elasticsearch:
    host: 192.168.108.129
    port: 9200
    http: http
    username: elastic
    password: _UXrf_rjRQU2wiIL8*Ch
    cafingerprint: 4C2CFA5727D2B1211280FCB00661EF3ACAA9F8BA2A2CEA892727CE443BA3B9F1
  servlet:
    multipart:
      #      单个文件最大限制 类型是datasize，单位kb
      max-file-size: 999999
      #      单次请求最大限制
      max-request-size: 999999
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.129:3307/gaoweifeng?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.gwf.vul.api
#  application:
#    #服务名称
#    name: naocs-service
#    profiles:
#      active: dev
#    cloud:
#      nacos:
#        config:
#          # 配置文件的环境
#          group: ${spring.profiles.active}
#          # 配置文件的格式
#          file-extension: yaml
#          # 配置中心的地址
#          server-addr: 47.105.198.54:8848
#          # 配置文件prefix
#          prefix: ${spring.application.name}
#          #命名空间
#          namespace: mall

minio:
  endpoint: http://192.168.200.94:9000/
  accessKey: m6K3278EYLSGkGDZiYqx
  secretKey: oN8XPDF90UzqtOtaL2ZWK5jnV3MhiPtzv4JL0Pdd
  bucketName: gaoweifeng