apiVersion: apps/v1
kind: Deployment
metadata:
  name: vul
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vul
  template:
    metadata:
      labels:
        app: vul
    spec:
      containers:
        - name: vul
          image: vul:latest
          ports:
            - containerPort: 8080